### ISSUE TITLE
sonatype support library

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#10]
https://github.com/xerial/sbt-sonatype

**Comment by cvogt** [comment]
https://books.sonatype.com/nexus-book/reference/confignx-sect-plugins.html

**Comment by cvogt** [comment]
would be really nice to have. Putting on 1.1 right now

**Comment by cvogt** [comment]
It seems like this is the base url https://oss.sonatype.org/service/local/

And then there are paths below like
https://oss.sonatype.org/service/local/staging/profiles

Other urls and the relevant xml in the response can probably be extracted from this:

https://github.com/xerial/sbt-sonatype/blob/d34a8489d3a9c00ac8e6c8b7ffe6823ab0baf242/src/main/scala/xerial/sbt/Sonatype.scala#L574-L841

Looks like the docs for the REST api can be seen in the plugin page of the dashboard of a sonatype installation. See https://books.sonatype.com/nexus-book/reference/confignx-sect-plugins.html#fig-config-plugin-core-api-site

**Comment by cvogt** [comment]
one more thing you might want to take a look at @rockjam  :)  @mchav may have taken a stab at that already

**Comment by cvogt** [comment]
I'd suggest to start simple and only implement sonatypeRelease for now.

And it would be great if we’d use the JDK-builtin URLConnection to do the rest calls like the other parts of Lib. It's actually quite easy to use and not having to add extra dependencies is nice.

We have a little helper that takes proxy settings into account. Two usages so far. One here: https://github.com/cvogt/cbt/blob/551c473845fa49a545ed39f00b7cf9efd98dce65/stage1/Stage1Lib.scala#L63
one here https://github.com/cvogt/cbt/blob/551c473845fa49a545ed39f00b7cf9efd98dce65/nailgun_launcher/Stage0Lib.java#L159

**Comment by rockjam** [comment]
@cvogt 
> I'd suggest to start simple and only implement sonatypeRelease for now.

As I see from cbt's sources, publishSigned to oss.sonatype.org is already implemented. If I understand correctly, `close` and `promote` tasks are required to allow full publish to sonatype and maven central cycle. Am I right, or something else is missing?

**Comment by cvogt** [comment]
Yep. That's accurate.

**Comment by cvogt** [comment]
Regarding the required tasks, I think we need the equivalent of sbt-sonatype's `sonatypeRelease`, which requires the equivalent of sbt-sonatype's `sonatypeClose`

**Comment by rockjam** [comment]
Yes, I agree. I will share results as soon as I have progress. For now, I was able to publish and synchronise signed jars to Central repository.
