### ISSUE TITLE
pomExtra considered harmful !

### ISSUE THREAD

**Issue by MasseGuillaume** [cvogt/cbt#110]
POM is super simple: https://github.com/MasseGuillaume/super-winner/blob/master/src/main/scala/ch.epfl.scaladex/maven/Pom.scala#L14

`pomExtras` just lead to publishing invalid POM see https://github.com/sbt/sbt/issues/2566

with https://github.com/cvogt/cbt/issues/67 you would have a complete Typesafe alternative to pomExtras

**Comment by cvogt** [comment]
fixed in 10dbafc2117ba7b8e0183ac402176e7e815a5280
