### ISSUE TITLE
IntelliJ support

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#123]
Had a chat with @pavelfatin, on of the developers of the IntelliJ Scala plugin. He pointed to this api requirements list in order to have a build tools play nice with IntelliJ https://groups.google.com/forum/#!topic/sbt-dev/z0quggLy2JY

We should expose such an API and then see who writes a CBT plugin for IntelliJ.

**Comment by nafg** [comment]
Is the implication that you need to provide an sbt server API? Or that you have to meet the requirements he outlined there in whatever way shape or form, and then someone will write the intellij plugin part?

**Comment by cvogt** [comment]
I talked to him in person. In whatever shape or form seems sufficient. And someone writes a plugin, could be them or us or together.

**Comment by cvogt** [comment]
related gitter discussion https://gitter.im/cvogt/cbt?at=5765715d2a4cd63745ea966e

**Comment by cvogt** [comment]
One idea mentioned there was simply generating POM files to pull off integration quickly. Alternatively generating .iml/.idea files as https://github.com/mpeltonen/sbt-idea does. The IntelliJ guys themselves proposed exposing an interface they could call into.

**Comment by cvogt** [comment]
seems also related https://github.com/JetBrains/sbt-structure

**Comment by cvogt** [comment]
@prassee is taking a stab at generating intellij project definitions https://github.com/prassee/cbt-idea-plugin

probably eventually we'll need a real plugin, but for now that's super awesome

**Comment by darkfrog26** [comment]
Any updates on when this will be in the main release?  This is the only thing holding me back from trying to switch to using CBT.

**Comment by cvogt** [comment]
@prassee has PR https://github.com/cvogt/cbt/pull/194 open for an IntelliJ project generator. Like in the olden days before IntelliJ talked directly to SBT. I requested some changes. As soon as he updates, I'll merge. We definitely want to get at least basic support in for 1.0. I want to get 0.9 (https://github.com/cvogt/cbt/milestone/1) out by Scala Days Chicago and 1.0 (https://github.com/cvogt/cbt/milestone/5) at least good underway. Expect a lot of cleanup from 0.9 to 1.0 meaning API and type changes (e.g. io => nio).

**Comment by cvogt** [comment]
offered this as a GSOC project: https://www.scala-lang.org/gsoc/2017.html#cbt-ide-integration

**Comment by MasseGuillaume** [comment]
It look like this one is happening :)
https://summerofcode.withgoogle.com/projects/#5076262042206208

**Comment by cvogt** [comment]
It is indeed and this is the project plan: https://docs.google.com/document/d/14BQSOKGYL9-JqrO3ZTqcCJVy2LD1JAL6nXzScxYSU-c

**Comment by olafurpg** [comment]
Fantastic news! I am happy to dogfood early releases 😄  Lack of intellij support is currently the biggest blocker for me to give cbt a serious try.

**Comment by cvogt** [comment]
related PR to export build information: https://github.com/cvogt/cbt/pull/511

**Comment by cvogt** [comment]
@darthorimar released a first version and put up a quick getting started here: https://github.com/cvogt/cbt/blob/master/doc/intellij.md

**Comment by nafg** [comment]
Will it eventually be merged into upstream intellij plugin?

**Comment by cvogt** [comment]
It will either be merged or become a separate plugin. @darthorimar is working with the Jetbrains team in St. Petersburg, so I suppose both options are on the table.

**Comment by Kreinoee** [comment]
Should this ticket be closed, now that Intellij seems to have support for CBT: https://github.com/cvogt/cbt/blob/master/doc/intellij-gsoc.md ?

**Comment by cvogt** [comment]
yes :)! follow up to improve docs: https://github.com/cvogt/cbt/issues/574
