### ISSUE TITLE
fat jar

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#124]
we should allow generating fat jars. Probably as a plugin. It's been requested by multiple people

**Comment by cvogt** [comment]
just FYI @rockjam have you already worked on this? I just heard @mchav started prototyping something. You guys may wanna join forces. @mchav why don't you create a PR with whatever rough initial stage of things you have?

**Comment by rockjam** [comment]
@cvogt I began with experiments and prototyping. We can cooperate with @mchav I think, if he'll agree

**Comment by rockjam** [comment]
I have some success with it. Created simple fat jar from cbt project. Will try to publish something that works today

**Comment by mchav** [comment]
@rockjam I'd be more than happy to cooperatively with on it.
