### ISSUE TITLE
compiling a project's code with dotty

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#166]
now that dotty has a website and an sbt plugin it would be good to allow people to compile their projects with dotty.
We need a dotty ready icon ;)

official
http://dotty.epfl.ch/
http://dotty.epfl.ch/#getting-started
https://github.com/felixmulder/sbt-dotty

3rd party (?)
https://github.com/smarter/dotty-bridge
https://github.com/smarter/dotty-example-project

**Comment by cvogt** [comment]
@felixmulder Can one of you guys show me how to call dotty, programatically?

We need something that can be used in place of the code that calls zinc. Here is that code in CBT'S library right now: https://github.com/cvogt/cbt/blob/d23dd6040fdba7b201e5f15d7027030d5259ef8e/stage1/Stage1Lib.scala#L131

And here is the place where it is invoked from the build class:
https://github.com/cvogt/cbt/blob/d23dd6040fdba7b201e5f15d7027030d5259ef8e/stage2/BasicBuild.scala#L128

**Comment by felixmulder** [comment]
Thanks for putting out these issues. Calling Dotty programmatically should be possible by depending on one of the nightly releases in the same way as the example project in: https://oss.sonatype.org/content/repositories/releases/ch/epfl/lamp/dotty_2.11/

What you need to do is create a `Driver` from: https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/Driver.scala

This will give you an entry point into the compiler. I believe that incremental compilation has already been implemented by @smarter - he has better answers than I for this currently.

Also - yes! We should create a dotty ready icon! Great idea! :+1:

**Comment by felixmulder** [comment]
I'll take a closer look tomorrow morning, cheers!

**Comment by cvogt** [comment]
I think for starters calling `dotty.tools.dotc.Main.main` is fine. How does dotty handle incremental compilation. Do I get abstract method errors like in scalac if traits become incompatible, or is dotty smarter here?

If dotty is not smarter, how should we handle this? Let it fail and ask people to run cbt clean if they run into those?

**Comment by felixmulder** [comment]
Yes, that is also fine since it is one and the same:

```scala
// dotty.tools.dotc.Main
object Main extends Driver {
  override def newCompiler(implicit ctx: Context): Compiler = new Compiler
}
```

From what I can remember, we have a different scheme for hashing compiled assets so that recompilation should be more correctly triggered. Although, I cannot say with confidence exactly what the limits of this is.

**Comment by cvogt** [comment]
ok, let's go with dotty as is then and see where stuff breaks :). Should be easy enough to do, I'll take this one.

**Comment by cvogt** [comment]
implemented this: https://github.com/cvogt/cbt/pull/235

It does currently crash dotc. Would be great if you could take a look. The command line may already indicate what is wrong, possibly the classpath. If you need to reproduce it there are intructions.

**Comment by cvogt** [comment]
Done. Ready for review: #235

(fixed the crash I had at first)

**Comment by smarter** [comment]
As far as I know, you rely on zinc for incremental compilation, dotty will never support zinc 0.13 but if you can managed to get zinc 1.0 to work with cbt, I'll adapt dotty for it (this will have to be done anyway sooner or later because zinc 1.0 is the only way to do incremental compilation with sbt 1.0).

**Comment by cvogt** [comment]
fixed by https://github.com/cvogt/cbt/pull/235

@smarter Is there any other way to do incremental compilation with Scala? Created a ticket to upgrade zinc to 1.0 https://github.com/cvogt/cbt/issues/242

**Comment by smarter** [comment]
No, there isn't.
