### ISSUE TITLE
cbt console/repl task

### ISSUE THREAD

**Issue by rockjam** [cvogt/cbt#181]
We could create `cbt repl`/`cbt console` task, that will be equivalent to `scala -cp $(cbt classpath)`. We could rely on system installed scala distribution for example

**Comment by rockjam** [comment]
Could be there any difficulties here? We can make it similar to https://github.com/cvogt/cbt/blob/master/stage2/Lib.scala#L266

**Comment by cvogt** [comment]
I actually don't think so. Try this `cbt tools scala 2.11.6`. Works well through nailgun. Not sure what didn't work with gpg there.

**Comment by rockjam** [comment]
So, `cbt repl` should be equivalent to 
`cbt tools scala $(cbt scalaVersion) -cp $(cbt classpath)`, right? 
The easiest solution could be - to create some kind of alias. What do you think about solution like this?

**Comment by rockjam** [comment]
`cbt tools scala $(cbt scalaVersion) -cp $(cbt classpath)` actually works as expected

**Comment by cvogt** [comment]
I guess you could start with just making a process call ;). Also if you check out `cbt tools scala 2.11.8` that stopped working for me somehow. `2.11.6` is fine.

**Comment by cvogt** [comment]
This is currently affected but not blocked by https://github.com/cvogt/cbt/issues/236

**Comment by rockjam** [comment]
Tried it without nailgun - works fine

**Comment by cvogt** [comment]
looks like this was fixed by https://github.com/cvogt/cbt/pull/265
