### ISSUE TITLE
CBT Versioning

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#19]
In order to have reproducibility, builds probably should be able to specify a version of CBT they should be compiled with. One option would be a build.properties file just like SBT does it.

CBT would need to download the appropriate CBT version in order to compile a given build.

Also, CBT is extended via traits. How does that relate to different CBT versions. If CBT releases version 1.1, can users use plugins developed for 1.0 if they are compatible in some way (source or binary)? How?

@tpolecat would be great to have a session about this tomorrow. @milessabin this sort of falls into the category of compiling different typelevel libraries together, which I assume would not upgrade CBT all at the exact same time, so maybe we can join or overlap this session with that session.

**Comment by tpolecat** [comment]
Yeah I would love to talk about this. I'll try to get up to speed a little bit in the morning. I have a fork but haven't gotten it running yet.

**Comment by cvogt** [comment]
as decided on NEScala2016 for now, we use a convention where the build/build.scala file contains a structured comment on the top of the file, specifying the cbt version, e.g. something like
```
//cbt:1.0
class Build
```
(attendents @tpolecat @softprops @guillauemasse @clhodapp and a few more)

**Comment by farmdawgnation** [comment]
Would cbt process that comment somehow?

**Comment by cvogt** [comment]
@farmdawgnation (Sorry forgot to record audio in the meeting.) Yes. It was @tpolecat's idea. CBT would read it, automatically fetch the required CBT and use that to build that project. The comment seems a little nicer than a separate build.properties file as sbt uses.

Regarding how and where CBT fetches the version from we discussed either binaries from MavenCentral or sources directly from GIT. I think @tpolecat @softprops @clhodapp and I all leaned towards distributing as source from git. @clhodapp suggested to use the git repository url and a reference instead of a version number. E.g.
```
// built with cbt git://github.com/cvogt/cbt.git#1.1
```

**Comment by cvogt** [comment]
We also discussed plugins, which are easier to distribute as source as well, so they don't have to bet cross-compiled against different scala and cbt versions (and their combinations). That could be done by simply allowing `GitDependency("git://github.com/cvogt/cbt-sonatype.git#0.5.1")`. The nice thing I realized is, that git dependencies and a mechanism, that downloads them into some cache and builds it from there, immediately solves the same problem for CBT version, too. Simply the default BuildBuild woud need to read the git url from the parent and add a git dependency for it, which is then used to compile and run the build it is responsible for. cc @tpolecat @softprops   I can implement that and we'll take a look. I'll open a PR.

**Comment by farmdawgnation** [comment]
> suggested to use the git repository url and a reference instead of a version number

This would immediately insulate from issues where the repository moves without any effort in the code. (E.g. if a cbt organization appeared and the repo was moved there... in that case github's 302 redirects should take care of redirecting the request to the correct location).

All of this is very interesting.

**Comment by cvogt** [comment]
yep, and it would also allow people to fork cbt and write builds against those as well.

**Comment by farmdawgnation** [comment]
I'm :+1: on this. :)

**Comment by shshe** [comment]
This is very exciting! There's support for git-based dependencies within the Python pip world that you might want to use as a reference for syntax:
https://pip.pypa.io/en/stable/reference/pip_install/#git

**Comment by cvogt** [comment]
step one is done. @chavxo and I implemented git dependencies. https://github.com/cvogt/cbt/pull/91
Next step is letting the default BuildBuild parse the sbt version tag from it's managedBuild and use that CBT version to run it. There will probably be some complication to get the classloading etc. right and communicating across classloader/version boundaries. For the version tag I currently envision this format:
//cbt-version:git://github.com/cvogt/cbt.git#afeddedaae312ea4112334114    (encouraging to use stable hashes or potentially even enforce it.)

**Comment by cvogt** [comment]
Implemented in https://github.com/cvogt/cbt/pull/111/commits/53247b5610b0168a3dd93d3d8f1224b78995ecde
Fixed in https://github.com/cvogt/cbt/pull/114

Here is the test case showing usage:
https://github.com/cvogt/cbt/blob/fix-tests/test/simple-fixed/build/build.scala#L5

CBT looks for a cbt url in this format
`// cbt:file:///Users/chris/code/cbt/#bdd6d905807a8cee7655d436401e76196ec4fe67`
(Didn't go with https://pip.pypa.io/en/stable/reference/pip_install/#git `@` syntax for now, but using a `#` like SBT does.)

This is a huge step forward!

It also enables source plugins a envisioned (cc @clhodapp). There is one for ScalaTest in https://github.com/cvogt/cbt/tree/master/plugins/scalatest but it can only be used via a local BuildDependency until https://github.com/cvogt/cbt/issues/117 is fixed.
