### ISSUE TITLE
sbt-like scoping of tasks

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#210]
If I am not mistaken you can get the exact equivalent of sbt's task scoping, by inspecting the current stack trace and checking if a particular method was called before. E.g. sbt's

```
scalaVersion in compile := "2.12.0-M2
```

is the exactly same as cbt's

```
override def scalaVersion = {
  if(new Exception().getStackTrace.containsMethod("compile")) "2.12.0-M2"
  else super.scalaVersion
}
```

(assuming we implemented a method containsMethod that checks if a method with the given name was called on a subclass of BaseBuild anywhere on the stack trace)

This may seem crazy, but seems isomorphic to sbt's scoping meaning its not more or less crazy, just the same if you will. Some use cases seem to require this, so we may as well consider this under some nice, safe interface. The performance penalty of generating stack traces seem neglegible in this setting. They are far below anything else, lead by scalac's compile times ;).

**Comment by cvogt** [comment]
We should document that this makes things much harder so should really only be used when really needed.

**Comment by nafg** [comment]
Please make things statically deterministic

**Comment by nafg** [comment]
I.e., inspecting the stack trace is probably worse than reflection in respective situations.

What are we trying to solve?

**Comment by cvogt** [comment]
> Please make things statically deterministic

not sure what regards to, but it seems to me like it is with the exception of runtime input.

> What are we trying to solve?

In sbt the return value of tasks can depend on who called them (even transitively, right). To match that feature in CBT, methods could inspect the stack trace. The use case for this is for example the scalaJsPlugin. We currently have this, where the plugin author has to hard code which things can be scoped in what:

```scala
  def scalaJsOptions: Seq[String] = foo
  def scalaJsOptionsFastOpt: Seq[String] = scalaJsOptions
  def scalaJsOptionsFullOpt: Seq[String] = scalaJsOptions

  def fastOptJS = {
    compile
    link(FastOptJS, fastOptJSFile, scalaJsOptionsFastOpt)
    fastOptJSFile
  }
  def fullOptJS = {
    compile
    link(FullOptJS, fullOptJSFile, scalaJsOptionsFullOpt)
    fullOptJSFile
  }
```

A user can overwrite settings for one of the two cases like this

```scala
   override def scalaJsOptionsFastOpt: Seq[String] = bar
```

With the proposed solution the library author does not need to hard-code this. BaseBuild would define a method like this (or maybe as a macro that takes the actual method call rather than the string name as argument)
```scala
  protected def in(methodName: String) = new Exception().getStackTrace.containsMethod(methodName)) 
```

This is what the ScalaJS plugin would look like
```scala
  def scalaJsOptions: Seq[String] = foo

  def fastOptJS = {
    compile
    link(FastOptJS, fastOptJSFile, scalaJsOptions)
    fastOptJSFile
  }
  def fullOptJS = {
    compile
    link(FullOptJS, fullOptJSFile, scalaJsOptions)
    fullOptJSFile
  }
```

Here is how a user would customize settings for one task
```scala
   override def scalaJsOptions: Seq[String] = if(in("fastOptJs")) bar else super.scalaJsOptions
```


Not having this feature, for ScalaJS we get away with more manual work. But we also may prevent certain things the library author did not anticipate. SBT certainly decided that this kind of scoping is needed. 

Code is already hard to understand in the context of overrides, scoping makes it even harder, but some use cases seem to require this complexity (if it turns out this is wrong, great, then we'll never implement it, but at least now we have a solution described for when we do). Obviously it should be avoided, whenever it is not required.

"patching" scoping on top of the classic inheritance model in this way has the advantage that most of it is known to users, rather than a custom graph interpreter as SBT does, where everything is new or different.

**Comment by nafg** [comment]
I think this demonstrates that sometimes using a tool that's too simple
just makes the complexity surface somewhere else.
If tasks were monads instead of just method calls, wouldn't that solve this?

**Comment by cvogt** [comment]
I don't think "too simple" is the right term. Classical inheritance seems to satisfy many use cases, but not all. For more sophisticated ones we can add something on top. No need to throw the whole thing away and implement everything from scratch with a completely syntax/api. That's what SBT basically does with it's Task Applicative (or is it a Monad)? So yes, you can use a Monad, but there is no re-use of familiar concepts for configuration or evaluation strategy but re-use of familiar concepts where possible is what CBT is shooting for.

Did I understand you correctly?

**Comment by cvogt** [comment]
here is another use case and a potential solution to scoping-related use cases without actually introducing scoping: https://github.com/cvogt/cbt/issues/239

**Comment by cvogt** [comment]
I don't know SBT's task scoping well enough to be sure, but I think that dynamic overrides basically solve this as implemented here https://github.com/cvogt/cbt/pull/300 (without inspecting stack-traces, but just via inheritance and overrides). This is also somewhat related: https://github.com/cvogt/cbt/pull/303

An example is in `plugins/essentials/PublishDynamic.scala`:
```scala
  def publishSnapshotLocal: Unit =
    newBuild[PublishDynamic]{"""
      override def version = super.version ++ "-SNAPSHOT"
    """}.publishLocal
```

this should be equivalent to something like sbt's

```sbt
publishSnapshotLocal := {
  (version in publishLocal) := ( version.value ++ "-SNAPSHOT" )
  publishLocal.value
}
```
