### ISSUE TITLE
consider using Apache 2.0

### ISSUE THREAD

**Issue by fommil** [cvogt/cbt#27]
for the reasons outlined in http://fommil.github.io/scalasphere16/

**Comment by cvogt** [comment]
I need more info. I am not at all a licence expert, but Apache 2 seemed more restrictive. Very open to having a discussion about this, but probably after version 1.0 has been polished. Or is there urgency to do it before?

**Comment by fommil** [comment]
watch my talk and you'll understand :smile:

Apache is definitely not more restrictive, it's safer. The primary difference is that nobody can contribute their patented work to the project without also giving a free licence to all future users. You definitely want that.

**Comment by cvogt** [comment]
@tobias-johansson @tpolecat @farmdawgnation any opposition to doing this switch now?

**Comment by tobias-johansson** [comment]
No objections on my part
