### ISSUE TITLE
be aware of the danger of open file handlers on Windows

### ISSUE THREAD

**Issue by fommil** [cvogt/cbt#28]
see https://github.com/sbt/sbt/issues/2496 and the catch-all https://issues.scala-lang.org/browse/SI-9683

**Comment by cvogt** [comment]
so what's the solution? not caching would mean significant performance drop. But to cache you need to duplicate the files as it seems. Maybe we should never lock the central jars and always copy them into the project first

**Comment by fommil** [comment]
Central jars is a minor concern. Imagine you have a multi module project and you're compiling out to jars, then you get into situations where you can't update your own build jar because you've got a warm compiler classpath referencing the existing one, or a test runner that has got lost in gc. In the best case, you'll have a memory leak.

I think you need to treat classloaders as closeable / cacheable resources and let the user decide what they want to do anytime you're reusing one. I'd trade performance for correctness on windows anytime.

Copying of jars is an evil last resort hack. We have to do that in ENSIME to avoid the presentation compiler from interacting with the build jars. It's brings its own world of pain. Many other tasks such as testing and compilation have a similar impact and copying (for everything that could lock the files) is not a feasible solution.

**Comment by fommil** [comment]
I'd also like the know exactly what the performance benefit is. I never trust performance guesses until I've seen a scientific study on it, primarily because my own intuition has let me down so much.

**Comment by cvogt** [comment]
and this might be a drop-in solution: https://github.com/fommil/class-monkey

**Comment by fommil** [comment]
Actually I think the solution is to just write your own classloader. It's not hard. My workaround is because I can't change sbt or scalac but maybe cbt has the power to do that directly.

**Comment by fommil** [comment]
Btw, I think by having your own classloader you could actually get some speedups in compiles, of the order 5% faster maybe.

**Comment by cvogt** [comment]
Oh, I see. CBT uses all of it's own classloaders already, so I could just check to do the same of whatever you are doing there.

**Comment by fommil** [comment]
Basically writing LocalFilesystemClassLoader because it's 2016 and the information superhighway didn't work out the way SUN expected. Just make sure to close your files after every access, which I think might exclude NIO ZipFileSystem.

**Comment by fommil** [comment]
some completely gullible fools have hired me to write Haskell, so I'm closing all my Scala tickets :rofl:
