### ISSUE TITLE
date: invalid option -- 'j'

### ISSUE THREAD

**Issue by darkfrog26** [cvogt/cbt#338]
I'm trying to run CBT on Fedora 25 and ended up building nailgun from the source and I'm getting the following output when I attempt to run `cbt`:

```
Stopping background process (nailgun) if running
Compiling cbt/nailgun_launcher
date: invalid option -- 'j'
Try 'date --help' for more information.
touch: invalid date format ‘/home/mhicks/projects/third/cbt/nailgun_launcher/target/scala-2.11/classes/../classes.last-success’
Starting background process (nailgun)
connect: Connection refused
```

**Comment by darkfrog26** [comment]
Nevermind about the connection refused (problem with the ng-server script), but you may want to look into the date formatting issue.

**Comment by cvogt** [comment]
@darkfrog26 you also may want to try `cbt direct <task name>` instead of  `cbt <task name>` if you have trouble with the nailgun-based one.

The date thing, yeah. At some point osx syntax snuck in there. Changed the issue name to reflect that.
