### ISSUE TITLE
Looping on Linux

### ISSUE THREAD

**Issue by mchav** [cvogt/cbt#37]
Loop runs continuously and doesn't seem to watch for file changes.

**Comment by cvogt** [comment]
probably requires using the native JDK WatchService when not on OSX. It has the same api, so should be an easy port

**Comment by ChavXO** [comment]
Switched from OpenJDK to Oracle JDK. Works fine now.

**Comment by ChavXO** [comment]
Scratch that..compiling source is fine. Still happens when build has errors because it just restarts CBT.

**Comment by cvogt** [comment]
can you explain more. Does it loop or not? The library BarbaryWatchService cbt is using is advertised for OSX. I have no idea if it works on other systems, but we can use the JDK buildin one instead then. Somebody would just need to implement that switch.

**Comment by ChavXO** [comment]
If there is an error in the "build" file it restarts CBT and tries to recompile every time. If there is an error in the source file the watcher acts as expected.

**Comment by cvogt** [comment]
@ChavXO so just to be clear: Detecting fine changes and reacting to it works on linux? Could you check on windows as well (ideally with and without cygwin)? We should setup CI for that.

And if there is a compile error in CBT itself it keeps looping. This is a known issue, that needs fixing. to do with status codes.

**Comment by cvogt** [comment]
I hear this is not an issue any longer
