### ISSUE TITLE
cbt loop run does not re-compile on file save

### ISSUE THREAD

**Issue by olafurpg** [cvogt/cbt#405]
```
cbt tools createMain
cbt loop run
// file save triggers recompile + run
// save again with edit and no recompile, only run on stale file
```
I expected the the second save to trigger a recompile and run on the new file sources.

Note, it's possible to workaround this by Ctrl-c to exit `loop run` and restart `cbt loop run`.

**Comment by cvogt** [comment]
Please try this branch: https://github.com/cvogt/cbt/pull/420
