### ISSUE TITLE
Feature request: simple way to clear screen on every loop iteration

### ISSUE THREAD

**Issue by olafurpg** [cvogt/cbt#406]
In sbt, I usually set `triggeredMessage in ThisBuild := Watched.clearWhenTriggered`. This triggers `clear` to run on very file-save event before running compile/run/test. `clear` clears the console screen, so it's easy to distinguish console output between each run. It would be nice if it was easy/automatic to do something similar in cbt.

EDIT, I couldn't find any mention of "clear" in the readme or issue, so I opened this ticket. Maybe it's documented somewhere :/

**Comment by cvogt** [comment]
Documentation is scarce right now :). Looks like an ansi code does the job.
This clears the screen for me

**Comment by cvogt** [comment]
Support being added in https://github.com/cvogt/cbt/pull/420 as
```
override def loop{
  lib.clearScreen
  super.loop
}
```
