### ISSUE TITLE
GUI missing "New project created in .../new_project" message

### ISSUE THREAD

**Issue by olafurpg** [cvogt/cbt#421]
I ran `cbt tools gui` and created a project from scratch. When I clicked on the "Create project" button, nothing appeared on the screen, even though the project had been created in the background. When I clicked "Create project" again, I got a `FileAlreadyExistsException` in the terminal console.

I expected the UI to display a message saying the project had been created and I also expected the UI to display a message "Project already exists" when I clicked "Create project" for the second time.

PS. The gui is an amazing idea! I am a huge fan 👍

**Comment by cvogt** [comment]
@olafurpg the gui is @tim-zh's idea/project. It's all up to him :).

**Comment by tim-zh** [comment]
@olafurpg I'm happy to hear that :)
gui uses [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API), so either your browser doesn't support it, or you didn't give localhost the permission to show notifications. gui requests the permission every time it's opened.

**Comment by olafurpg** [comment]
@tim-zh I see, would it make sense to also display the "New project created" notification in the html? I did not notice that the page requested for permission to send notifications.

Also, this issue was partly twofold. The second issue is that if you press the "Create project" twice, it will crash with an FileAlreadyExists exception.

**Comment by tim-zh** [comment]
Actually, it's not a crash :). IMHO, it's a part of `cbt`'s ideology ( @cvogt please correct me if I'm wrong) to show what's really happening. In this case there is no complete certainty that a "project already exists", maybe there are leftovers from something, maybe forgotten mocks.

**Comment by cvogt** [comment]
generally cbt tries to not hide information that could be useful for the user (but also tries not to overwhelm, e.g. show some stuff only when logging is enabled)
