### ISSUE TITLE
port scalahost to cbt

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#458]
https://github.com/scalameta/scalameta/blob/master/scalahost-sbt/src/main/scala/scala/meta/scalahost/sbt/ScalahostSbtPlugin.scala

**Comment by olafurpg** [comment]
I'm happy to help out, I wrote the sbt-scalahost plugin. Is it possible to write cbt plugins outside the cbt repo?

**Comment by olafurpg** [comment]
I suspect the cbt plugin will require a lot less cermony, what's needed is 

1. inject -Xplugin:/scalahost.jar into project to analyze
2. `src/`  path of project to analyze
3. `classpath`/`target/` of project to analyze (important, scalahost.jar will emit `semanticdb` files in `target/` on compile)
4. ability to pass `src/` and `classpath` to some main function in a project that has a dependency on `org.scalameta:scalameta:xxx`

It's not necessary to use system properties to the classpath/sourcepath, it can be done as regular cli flags.

**Comment by cvogt** [comment]
@olafurpg re plugins outside the repo. sure. Just have a dependency on it. Typically a GitDependency.

**Comment by cvogt** [comment]
fixed in https://github.com/cvogt/cbt/pull/462
