### ISSUE TITLE
ScalaJS support

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#46]
assigning tentatively to milestone 1.1, but happier to get it in earlier

**Comment by sjrd** [comment]
The minimum minimorum is to be able to 1) compile and 2) link.

Compile is as easy as running the Scala compiler with `scalajs-library.jar` on the classpath, and `scalajs-compiler.jar` as a scalac plugin.

Linking is as easy as reproducing the code from the CLI linker at
https://github.com/scala-js/scala-js/blob/v0.6.7/cli/src/main/scala/org/scalajs/cli/Scalajsld.scala#L137-L177

Of course, that assumes people will then *run* their code on their own. But you probably want your build tool to allow them to run easily. That becomes a bit more tricky, but the core idea can be found at:
https://github.com/scala-js/scala-js/blob/v0.6.7/sbt-plugin/src/main/scala/scala/scalajs/sbtplugin/ScalaJSPluginInternal.scala#L561-L679

**Comment by katrinsharp** [comment]
@cvogt @sjrd I'll try to dig into it. Will keep you posted.

**Comment by cvogt** [comment]
Sounds awesome. Excited about this :). I am sure @sjrd and @gzm0 are happy to answer questions if they arise. Me too.

cc @lihaoyi

**Comment by cvogt** [comment]
assigned to @katrinsharp

**Comment by cvogt** [comment]
@katrinsharp everything is in place now in cbt to take a crack at this.

**Comment by katrinsharp** [comment]
@cvogt had some prior commitments so only played with the code so far, but will take it as commitment now.

**Comment by katrinsharp** [comment]
@sjrd question: why maven dependency scalajs-compiler artifact has full scala version 2.11.8 and not 2.11 ? (http://mvnrepository.com/artifact/org.scala-js/scalajs-compiler_2.11.8/0.6.9) Feels like a bug unless it is feature :)

**Comment by sjrd** [comment]
It is a feature. The compiler API is neither source nor binary compatible between minor versions of Scala, so compiler plugins must always be fully cross-compiled.

**Comment by cvogt** [comment]
https://github.com/cvogt/cbt/pull/121

**Comment by katrinsharp** [comment]
#144

**Comment by cvogt** [comment]
basic support implemented in #144
