### ISSUE TITLE
Two ctrl-Cs should be enough

### ISSUE THREAD

**Issue by paulp** [cvogt/cbt#490]
Hitting ctrl-C twice with nothing happening in between ought to be sufficiently convincing to quit. I have to hold it down pretty convincingly, leaving me typically with 
```
Watching for file changes... (ctrl+c short press for loop, long press for abort)
^C^C
^C
^C
^C
^C
^C
^C
```
If it I time it juuuuuuuust right I only get about three of them, but when I want to bail out it shouldn't feel like a carnival game not to advance my scrollback buffer ten lines.

**Comment by cvogt** [comment]
hehe, yeah. That's all an artifact of using `fswatch` from the bash script. Not sure how to solve it. Any ideas?

**Comment by paulp** [comment]
Set a trap in the bash script.
```bash
onCtrlC () { exit 0; } # or whatever
trap onCtrlC INT
```
That would exit on the first interrupt. It could carry some state and not exit until the second interrupt but honestly I'm not sure what use case that is intended to serve.

**Comment by cvogt** [comment]
Sounds good
