### ISSUE TITLE
Build failed with `java.lang.NoClassDefFoundError: Could not initialize class com.datastax.driver.core.Cluster`

### ISSUE THREAD

**Issue by amsayk** [cvogt/cbt#512]
Sample project here: https://github.com/amsayk/phantom-playground

Added `MavenDependency("com.datastax.cassandra", "cassandra-driver-core", "3.2.0")` but same error.

**Comment by cvogt** [comment]
try either of `cbt direct compile` or `override def flatClassLoader = true` or `override def fork = true` or both of the last two. CBT isolates classloaders by default similar to jigsaw or osgi, but this disables it.

**Comment by amsayk** [comment]
Either override def flatClassLoader = true or override def fork = true or both works.

Thanks.

**Comment by cvogt** [comment]
Nice! In that case I can recommend flatClassLoader as it is slightly faster in some cases, otherwise not slower.
