### ISSUE TITLE
Compile error when trying to use cbt on Windows

### ISSUE THREAD

**Issue by frankwhofmann** [cvogt/cbt#561]
Followed instructions in Tutorial/Installation. Tried with both 'master' and '2.12.1' branches (as I have Scala 2.12. installed), but in both cases the sbt didn't came up, but produced the following compile error. Hoping to get a hint here.
BTW: Nailgun server was running. I don't know what it could mean (in the program ouput) to 'install Nailgun server' on any machine, be it windows or Linux.

D:\WORKSPACES\SWDEV\github-clones\github-root\cvogt>git clone -b 2.12.1 https://github.com/cvogt/cbt.git
Cloning into 'cbt'...
remote: Counting objects: 6042, done.
remote: Total 6042 (delta 0), reused 0 (delta 0), pack-reused 6041
Receiving objects: 100% (6042/6042), 1.27 MiB | 853.00 KiB/s, done.
Resolving deltas: 100% (3509/3509), done.
Checking connectivity... done.

D:\WORKSPACES\SWDEV\github-clones\github-root\cvogt>cbt
You need to install Nailgun Server to make CBT slightly faster.
You need to install gpg for login.
Note: nc not found. It will make slightly startup faster.
Compiling cbt/nailgun_launcher
D:\WORKSPACES\SWDEV\github-clones\github-root\cvogt\cbt\nailgun_launcher\NailgunLauncher.java:8: error: package cbt.reflect does not exist
import cbt.reflect.TrapSystemExit;
                  ^
D:\WORKSPACES\SWDEV\github-clones\github-root\cvogt\cbt\nailgun_launcher\Stage0Lib.java:15: error: package cbt.reflect does not exist
import cbt.reflect.TrapSystemExit;
                  ^
D:\WORKSPACES\SWDEV\github-clones\github-root\cvogt\cbt\nailgun_launcher\NailgunLauncher.java:72: error: cannot find symbol
    System.setSecurityManager( TrapSystemExit.createSecurityManager(initialSecurityManager) );
                               ^
  symbol:   variable TrapSystemExit
  location: class NailgunLauncher
D:\WORKSPACES\SWDEV\github-clones\github-root\cvogt\cbt\nailgun_launcher\Stage0Lib.java:26: error: cannot find symbol
      new TrapSystemExit<Integer>(){
          ^
  symbol:   class TrapSystemExit
  location: class Stage0Lib
D:\WORKSPACES\SWDEV\github-clones\github-root\cvogt\cbt\nailgun_launcher\Stage0Lib.java:25: error: cannot find symbol
    return TrapSystemExit.run(
           ^
  symbol:   variable TrapSystemExit
  location: class Stage0Lib
5 errors

D:\WORKSPACES\SWDEV\github-clones\github-root\cvogt>

**Comment by sake92** [comment]
@frankwhofmann can you try now? I've been working on `cbt.bat` recently, and it should work now. Note that there are still some bugs to be discovered.

**Comment by cvogt** [comment]
I'll close this for now as fixed. Please re-open if it doesn't work.
