### ISSUE TITLE
sbt does allow lazy dependencies

### ISSUE THREAD

**Issue by jroper** [cvogt/cbt#60]
The README says sbt doesn't allow lazy dependencies.  This is false, sbt does so allow lazy dependencies:

```scala
val flag = taskKey[Boolean]("a flag")
val taskA = taskKey[Unit]("task a")
val taskB = taskKey[Unit]("task b")
val dependentTask = taskKey[Unit]("dependent task")

taskA := println("task a")
taskB := println("task b")
flag := true

dependentTask <<= (flag, taskA.task, taskB.task).flatMap { (flag, a, b) =>
  if (flag) a else b
}
```

Running it shows that tasks A and B are lazily depended on:

```
> dependentTask
task a
> set flag := false
> dependentTask
task b
> 
```

**Comment by cvogt** [comment]
@jroper thanks, good to now.  Corrected in #61

For reference, here is the SBT equivalent
```
def flag = true
def a = println("task a")
def b = println("task b")
def dependentTask = if(flag) a else b
```

The question about how to dynamically replace `flag` with `false`in CBT is still open. Right now it would take creating another build that's based on the original and overrides the member. Related issue is #62
