### ISSUE TITLE
simple install

### ISSUE THREAD

**Issue by MasseGuillaume** [cvogt/cbt#66]
It would be nice to install cbt easily
* mac
  * [ ] brew install cbt
* linux
  * [ ] apt-get
  * [ ] nix
  * [ ] yum
  * ...
* window
  * [ ] chocolatey
  * [ ] msi

**Comment by cvogt** [comment]
I actually like to tell people to install using `git clone`. That makes it rather obvious that they can play with the code and where it is. It's cross platform, too. Do we really need all of these installers? I am tending towards wontfix. WDYT?

**Comment by MasseGuillaume** [comment]
+1 an easy way to play with the code.

However, there is some bootstrapping required like installing nailgun, etc. Let's close this issue for now.

**Comment by cvogt** [comment]
@MasseGuillaume so nailgun could be shipped as part of the git repo. zinc does that. gpg could be replaced by bouncy castle. realpath may be replaceable by some smarter solution to get the path
