### ISSUE TITLE
embed jar in sh file

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#7]
http://martiansoftware.com/lab/jar2sh

low priority

**Comment by cvogt** [comment]
one more thing you might want to take a look at @rockjam  :)  simimar to fatjar. And native packager supports this feature

cc @mchav

**Comment by mdedetrich** [comment]
I think this is something that would be better solved by an assembler or native-packager plugin

**Comment by cvogt** [comment]
closed in favor of https://github.com/cvogt/cbt/issues/483 https://github.com/cvogt/cbt/issues/484
