### ISSUE TITLE
properly detect if zinc succeeded or not.

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#76]
Currently it doesn't seem to communicate this via it's exist code.

That means we can't cache results, because we don't know if they succeeded. That leads to more calls to zinc than needed.

We also have to hope it succeeded when executing run and if it didn't we get exceptions.

A solution could be not using zincs runner. Probably the best way to do this is not calling zinc in stage1, but simply downloading it (using scalac to compile stage 2 instead). Then stage 2 can use zinc's typesafe api to configure it in a way that works as we need it.

**Comment by farmdawgnation** [comment]
I'm going to look into this.

**Comment by cvogt** [comment]
zinc's runner code is here https://gist.github.com/cvogt/c60672c3c17aa939dd92
