### ISSUE TITLE
More intelligent handling of recompiles when zinc fails.

### ISSUE THREAD

**Issue by farmdawgnation** [cvogt/cbt#83]
Currently, when zinc fails to compile a project we hit the last updated timestamp of each of the source files in the project to ensure that when the compile command is run again we actually recompile those files. This is because we look at the oldest class file in the target folder and then see if there are any source files newer than that. In the case of a partial compile, this won't necessarily be the case.

The current proposed solution is to use a file to store the last successful compile time somewhere, but I think sbt does this somehow _without_ doing that, so looking at their implementation might be worthwhile.

**Comment by cvogt** [comment]
fixed by 57de439
