### ISSUE TITLE
ENSIME plugin?

### ISSUE THREAD

**Issue by fommil** [cvogt/cbt#89]
we'd be happy to support you to write a `.ensime` generator so that people could use cbt with ENSIME.

Some documentation to get you started here http://ensime.github.io/build_tools/

**Comment by cvogt** [comment]
Sounds like a perfect project for a rather self-contained contribution :). Probably wiser to do this after CBT's apis stabilized a bit more.

**Comment by fommil** [comment]
placeholder docs in place http://ensime.github.io/build_tools/cbt/

**Comment by cvogt** [comment]
https://github.com/cvogt/cbt/issues/123 would probably provide the necessary API to realize this
