### ISSUE TITLE
Add tut to cbt's own build

### ISSUE THREAD

**Issue by cvogt** [cvogt/cbt#97]
https://github.com/tpolecat/tut / https://bintray.com/tpolecat/maven/tut-core

Time to write some proper docs :). Let's add tut to CBT's own build. I set up the basics to get started here: https://github.com/cvogt/cbt/pull/96

We can turn this into a plugin later. Should be trivial, once we have it.

**Comment by cvogt** [comment]
@tpolecat

**Comment by tpolecat** [comment]
Hi, sorry I didn't have a chance to look at this over the weekend. I'll take a look tomorrow.

**Comment by cvogt** [comment]
No worries. You won't be able to run tut until I or someone fixes the bug mentioned in the PR (I'll look into it with top priority), but I suppose you could just try writing the code without trying that it works for now.

**Comment by cvogt** [comment]
@tpolecat alright, got the classloading under control. tut as a build time dependency works now. I rebased #96 on the latest master that has the fixes and aded a commit enabling the dependency. The current code just does `println(TutMain)` in cbt's `build/build.scala`. That's the place where it would need to be replaced with the proper logic. Use `cbt tut` in the main directory to trigger it.

Alternatively to a build-time dependency of cbts main build we could consider moving cbt's tut to a dependent build with it's own build file. But I am happy to rearrange things later if you make it work in any way :).

**Comment by cvogt** [comment]
call is still open wether to use tut as people are familiar with markdown or a scala templating solution such as scalatex or scalate, which would be more extensible without writing markdown plugins.

closing this, we still have the general documentation ticket: https://github.com/cvogt/cbt/issues/352
